<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TargetGrps.Partelisto.Mcp.Application\TargetGrps.Partelisto.Mcp.Application.csproj" />
    <ProjectReference Include="..\TargetGrps.Partelisto.Mcp.Infrastructure\TargetGrps.Partelisto.Mcp.Infrastructure.csproj" />
  </ItemGroup>

</Project>
